In [2]:
import numpy as np

# int array
areuh = np.array([1, 4, 2, 5, 3.14])
print(type(areuh))
# tout en float : np.array([1, 2, 3, 4], dtype='float32')
np.array([range(1, 1+3) for i in [2, 4, 6]])


<class 'numpy.ndarray'>


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

la syntaxe de `[f(x) for x in another_list]` crée une liste en appliquant la fonction f() à chaque membre de another_list

In [3]:
# Un tableau de 10 entiers qui valent 0
np.zeros(10, dtype=int)

# Un tableau de taille 3x5 rempli de float de valeur 'ones'
np.ones((3, 5), dtype=float)

# Un tableau 3x5 rempli de 3,14
np.full((3, 5), 3.14)

# Un tableau rempli d'une séquence linéaire
# commençant à 0 et qui se termine à 20, avec un pas de 2
np.arange(0, 20, 2)

# Un tableau de 5 valeurs, espacées uniformément entre 0 et 1
np.linspace(0, 1, 5)

# Celle-ci vous la connaissez déjà ! 
# il y a aussi "randint" et "normal"
np.random.random((3, 3))

# La matrice identité de taille 3x3 
# (matrice identité : https://fr.wikipedia.org/wiki/Matrice_identit%C3%A9)
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)  # Tableau de dimension 1
print("nombre de dimensions de x1: ", x1.ndim)
print("forme de x1: ", x1.shape)
print("taille de x1: ", x1.size)
print("type de x1: ", x1.dtype)

nombre de dimensions de x1:  1
forme de x1:  (6,)
taille de x1:  6
type de x1:  int64


In [5]:
print(x1)

# Pour accéder au premier élément
print(x1[0])

# Pour accéder au dernier élément
print(x1[-1])

x2 = np.random.randint(10, size=(3, 4))  # Tableau de dimension 2
print(x2[0,1])

# On peut aussi modifier les valeurs
x1[1] = "1000"
print(x1)

# Attention au type
x1[1] = 3.14
print(x1)


[5 0 3 3 7 9]
5
9
5
[   5 1000    3    3    7    9]
[5 3 3 3 7 9]


In [7]:
print(x1[:5])  # Les cinq premiers éléments

print(x1[5:])  # Les éléments à partir de l'index 5

print(x1[::2])  # Un élément sur deux

print(x1[::-1])  # inversion d'un tableau

[5 3 3 3 7]
[9]
[5 3 7]
[9 7 3 3 3 5]


In [8]:
print(x2)

x2[0,:] # La première ligne

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


array([3, 5, 2, 4])

In [13]:
# concaténation
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertical concaténation
print(np.vstack([x, grid]))

# horizontal concaténation
print(np.hstack([grid, grid]))

[[1 2 3]
 [9 8 7]
 [6 5 4]]
[[9 8 7 9 8 7]
 [6 5 4 6 5 4]]


Les boucles peuvent être lentes :

In [14]:
def calcul_inverse(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
print(calcul_inverse(values))

tableau_large = np.random.randint(1, 100, size=1000000)

# Ceci est une facilité des notebooks jupyter pour 
# mesurer le temps d'exécution d'une instruction
%timeit calcul_inverse(tableau_large)

[0.11111111 0.5        0.16666667 0.11111111 0.2       ]
1.35 s ± 19.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [15]:
%timeit (1.0 / tableau_large)

2.07 ms ± 5.48 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Fonctions universelles :


In [16]:
# Il y a tout d'abord des opération mathématiques simples
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # Division avec arrondi

x = [-2, -1, 1, 2]
print("La valeur absolue: ", np.abs(x))
print("Exponentielle: ", np.exp(x))
print("Logarithme: ", np.log(np.abs(x)))


x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
La valeur absolue:  [2 1 1 2]
Exponentielle:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithme:  [0.69314718 0.         0.         0.69314718]


Booléens

In [17]:
x = np.random.rand(3,3)
x > 0.5
np.where(x > 0.5)

(array([0, 0, 1, 1, 1, 2]), array([0, 1, 0, 1, 2, 1]))

Agrégation

In [18]:
L = np.random.random(100)
np.sum(L)
%timeit sum(tableau_large)
%timeit np.sum(tableau_large)

M = np.random.random((3, 4))
print(M)
# Notez la syntaxe variable.fonction au lieu de 
# np.fonction(variable). Les deux sont possibles si
# la variable est un tableau Numpy.
print("La somme de tous les éléments de M: ", M.sum())
print("Les sommes des colonnes de M: ", M.sum(axis=0))

54.9 ms ± 774 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
603 µs ± 3.58 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
[[0.81001412 0.08782143 0.15618846 0.73099033]
 [0.6427996  0.09425156 0.1035502  0.32354189]
 [0.3706353  0.87966194 0.44429964 0.67253984]]
La somme de tous les éléments de M:  5.316294300734639
Les sommes des colonnes de M:  [1.82344903 1.06173492 0.7040383  1.72707205]


Broadcating: désigne un ensemble de règles pour appliquer une opération qui normalement ne s'applique que sur une seule valeur à l'ensemble des membres d'un tableau numpy. Par exemple, pour les tableaux de même taille, les opérations comme l'addition s'appliquent normalement élément par élément.

In [25]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b
print(a + 5)

M = np.ones((3, 3))
print("M vaut: \n", M)
print("M+a vaut: \n", M+a)

a = np.arange(3)
# La ligne suivante crée une matrice de taille 3x1
# avec trois lignes et une colonne.
b = np.arange(3)[:, np.newaxis]
print(b, a)
print(a+b)

[5 6 7]
M vaut: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
M+a vaut: 
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[0]
 [1]
 [2]] [0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]]
